### ISSUE TITLE
Onboarding Screens

### ISSUE THREAD

**Issue by peculiaruc** [zurichat/zc_app_android#11]

**Comment by afhamu** [comment]
I'm working on this issue

**Comment by CephasPeter** [comment]
Issue has been implemented and fixed by @afhamu . 
To test it, click on this link
https://appetize.io/app/xxnhq7myw94xgnecbmbw1q9akr?device=pixel4&scale=75&orientation=portrait&osVersion=10.0

**Comment by markessien** [comment]
Issue is fixed.
