### ISSUE TITLE
user should be able to type messages

### ISSUE THREAD

**Issue by iAmEben** [zurichat/zc_app_android#148]
This feature makes it possible for the user to send messages. This can rightly be achieved using a custom EditText in the application.

**Comment by CephasPeter** [comment]
#148 Feat/dm type message

A user can now type his/her message and the send icon will respond accordingly. This solves issue number 148

Test the work [here](https://appetize.io/app/zb1hvpdkmeu22n0yvy8v8ynxkw)

**Comment by markessien** [comment]
Nice work :+1:
