### ISSUE TITLE
Create Side bar Navigation

### ISSUE THREAD

**Issue by Sammylex01** [zurichat/zc_app_android#21]
Navigation drawer for side bar

**Comment by Success0452** [comment]
Implemented the Side bar Navigation 

[Click here to test](https://appetize.io/app/mdxb4jnm37j91tbem36qqapdjc)
[Access pull request here](https://github.com/zurichat/zc_app_android/pull/223)



https://user-images.githubusercontent.com/52849344/131422632-03909f15-3967-4db8-9bb8-85806fb4bfbb.mp4
