### ISSUE TITLE
Copy a message

### ISSUE THREAD

**Issue by logickoder** [zurichat/zc_app_android#23]
As a user, I will like to be able to able to copy a message

**Comment by ChibuFirst** [comment]
This enables a user to copy any message in the conversations

Once the user long press on a message, a context menu is displayed and the user selects "Copy" which automatically adds the selected message to the clipboard.

Live testing link:
https://appetize.io/app/y1fnmgwganezzxjwn8zf4bwyd8?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

Video Showing A Preview Of What has been done:
https://user-images.githubusercontent.com/52785343/131971703-c12b43a6-3b0b-4c21-acdf-6248a17deab5.mp4
