### ISSUE TITLE
Chat settings XML Layout

### ISSUE THREAD

**Issue by adelawson** [zurichat/zc_app_android#238]
create the XML Layout for the user to edit chat settings

**Comment by adelawson** [comment]
-Implemented chat preferences XML Layout with values for options with Icons as designed in the UI
- made test version where chat preferences page comes immediately after onboarding screen for testing [here](https://appetize.io/app/deryqzwwqjjgg1zqmtn9pduu6w)
![image](https://user-images.githubusercontent.com/30274219/131886511-420ed47e-51d0-484a-b7a1-34c05fe2c91d.png)

**Comment by CephasPeter** [comment]
Issue Solved and Ready to go. 
It can be tested here
https://appetize.io/app/deryqzwwqjjgg1zqmtn9pduu6w

**Comment by markessien** [comment]
ok
