### ISSUE TITLE
Turn off/on Message tones toggle switch

### ISSUE THREAD

**Issue by dapoanjorin** [zurichat/zc_app_android#273]

**Comment by dapoanjorin** [comment]
Users now have the option of toggling on or off sound for incoming messages. It can be accessed by clicking on notification and sounds 

Test link [here](https://appetize.io/app/cpufz4m0adj8zqmbtf9vh453kc)


![Screenshot from 2021-09-03 00-33-19](https://user-images.githubusercontent.com/32529582/131929041-e5ef42ca-e15f-4fd0-94d1-d39aa537529c.png)

**Comment by markessien** [comment]
ok
