### ISSUE TITLE
Profile Bottom Sheet Items

### ISSUE THREAD

**Issue by peculiaruc** [zurichat/zc_app_android#335]
This issue is fixed here #336 
Linked the profile camera to the bottom sheet
It displays bottom sheet list
From the bottom sheet, users can navigate to camera, gallery, or delete a photo
Here is the test link
https://appetize.io/app/008bapk2xz270f3fhefr1kt998?device=nexus5&scale=75&orientation=portrait&osVersion=8.1

**Comment by peculiaruc** [comment]
![PROFILE](https://user-images.githubusercontent.com/35475543/132118220-bf2f6542-bbde-4d90-bf55-9eddb301b515.png)

**Comment by CephasPeter** [comment]
#335 Profile Bottom Sheet Items

This PR:

Linked the profile camera to the bottom sheet
It displays bottom sheet list
Here is the test link
https://appetize.io/app/008bapk2xz270f3fhefr1kt998?device=nexus5&scale=75&orientation=portrait&osVersion=8.1
