### ISSUE TITLE
Turn on/off notification vibration 

### ISSUE THREAD

**Issue by krysnkem** [zurichat/zc_app_android#45]
The user should be able to turn on or turn off notification vibration.

**Comment by EbubeCode** [comment]
I implemented the toggle option for user to turn/off notification vibration. Follow this [Link](https://appetize.io/app/q5c41zjajbwuhep218e5bkn4km?device=nexus5&scale=75&orientation=portrait&osVersion=8.1) to test it on appetize.io. 
When you get to the settings screen,
![Screenshot_20210903-092719](https://user-images.githubusercontent.com/61353651/131980635-e1b25f34-33d8-4c91-88b9-6b0c0c790c16.png)
Click on Notification and sounds to view the toggle button for vibrate.
![Screenshot_20210903-092707](https://user-images.githubusercontent.com/61353651/131981404-5697de68-b7e5-4f73-be76-02ee880fad18.png)
