### ISSUE TITLE
Channel Chat Screen

### ISSUE THREAD

**Issue by Nwevopeace** [zurichat/zc_app_android#53]

**Comment by Success0452** [comment]
[Click here to test](https://appetize.io/app/5tp972cmu0fed1a4mwv9yx)

Username: Famous0452
Interface image
![Screenshot_20210902-095637](https://user-images.githubusercontent.com/52849344/131835121-52c3737a-8f39-4567-92d3-7bcc38d05f61.png)

**Comment by markessien** [comment]
Error loading app, please verify URL

**Comment by Success0452** [comment]
Updated!!
